### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by Kizero1998** [LordOfPolls/Rule34-Downloader#17]
I get Trojan warning from Defender. What's that?

**Comment by Kizero1998** [comment]
Ymacco.AA38

**Comment by LordOfPolls** [comment]
Yeah I got a similar warning the other day. I can assure you that this isnt a trojan. I've reported it as a false positive but theres not much more I can do unfortunately. My assumption would be that due to how the file is compiled, and the behaviour causes anti-viruses to freak out, which is fair, its making an excessive amount of requests. 

If youre concerned, id suggest running the py file instead, as you can see the raw source code.

**Comment by LordOfPolls** [comment]
New exe for the V2 release is not showing up as a trojan on any scans ive run, so im closing this issue. If this issue comes back, ill reopen
