### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by Anonwxyz** [LordOfPolls/Rule34-Downloader#20]
Avast Antivirus stops the download of the 3 most recent releases and says that they are infected with trojans.
You could make a github action so that anytime a new commit is committed, a new version could be released directly from the code.
Maybe this would help?

![image](https://user-images.githubusercontent.com/78394758/106543555-da7c1300-64fd-11eb-8dd0-c9600e3f00fe.png)

**Comment by LordOfPolls** [comment]
>[Insert antivirus here] says this is a virus

>>    I can assure you, this is not a virus. I'm not entirely sure why anti-viruses sometimes flag this as a virus, at a guess, I assume its because of how many requests it makes. Either way, if you're worried, you can see the source code, and run straight from the py file

As for releases, I dont want to make a release per commit, as that defeats the point of releases. That said, there is an exe uploaded with every commit in the ``dist`` folder. The issue is each exe may have a slightly different signature, but the behaviour is mostly the same, so it doesnt take long for an antivirus to add it to its database
